### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by DanBrown47** [howCodeORG/Simple-Python-Blockchain#3]
Traceback (most recent call last):
  File "/home/kasper/Desktop/INSIGHT/block.py", line 59, in <module>
    blockchain.mine(Block("Block " + str(n+1)))
  File "/home/kasper/Desktop/INSIGHT/block.py", line 48, in mine
    for n in range(self.maxNonce):
MemoryError

**Comment by DanBrown47** [comment]
Solved
